version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: cssnano
    versions:
    - 5.0.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.4
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: "@wordpress/dependency-extraction-webpack-plugin"
    versions:
    - 3.0.0
    - 3.1.0
    - 3.1.1
    - 3.1.2
  - dependency-name: "@wordpress/prettier-config"
    versions:
    - 1.0.2
    - 1.0.3
  - dependency-name: "@wordpress/env"
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.2
  - dependency-name: "@wordpress/babel-preset-default"
    versions:
    - 5.0.0
    - 5.1.0
    - 5.2.0
    - 5.2.1
  - dependency-name: "@wordpress/eslint-plugin"
    versions:
    - 8.0.0
    - 9.0.0
    - 9.0.1
    - 9.0.2
    - 9.0.3
  - dependency-name: postcss-import
    versions:
    - 14.0.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.6.0
  - dependency-name: stylelint
    versions:
    - 13.11.0
    - 13.12.0
  - dependency-name: "@wordpress/browserslist-config"
    versions:
    - 3.0.0
  - dependency-name: "@wordpress/babel-plugin-import-jsx-pragma"
    versions:
    - 3.0.0
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.6.0
